# Generated by Django 5.1.5 on 2025-01-24 07:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Заголовок")),
                (
                    "media",
                    models.CharField(max_length=256, verbose_name="Название источника"),
                ),
                (
                    "media_link",
                    models.CharField(
                        max_length=256, verbose_name="Ссылка на сайт источника"
                    ),
                ),
                (
                    "media_data",
                    models.DateTimeField(verbose_name="Дата и время публикации"),
                ),
                (
                    "preview_image",
                    models.CharField(
                        max_length=512,
                        verbose_name="Ссылка на картинку для отображения",
                    ),
                ),
                (
                    "preview_link",
                    models.CharField(
                        max_length=512, verbose_name="Ссылка на сайт для вставки"
                    ),
                ),
            ],
            options={
                "verbose_name": "СМИ",
                "verbose_name_plural": "СМИ",
                "db_table": "medias",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        upload_to="storage/images", verbose_name="Превью проекта"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=256, verbose_name="Заголовок проекта"),
                ),
                (
                    "description",
                    models.CharField(max_length=512, verbose_name="Описание проекта"),
                ),
                (
                    "customer",
                    models.CharField(max_length=64, verbose_name="Заказчик проекта"),
                ),
                (
                    "place",
                    models.CharField(
                        max_length=64, verbose_name="Площадка проведения проекта"
                    ),
                ),
                (
                    "photographer",
                    models.CharField(max_length=64, verbose_name="Фотограф"),
                ),
                (
                    "video_url",
                    models.URLField(
                        max_length=512, verbose_name="Ссылка на видео проекта"
                    ),
                ),
                (
                    "full_description",
                    models.TextField(verbose_name="Полное описание проекта"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WEDDING", "Свадьба"),
                            ("CORPORATE", "Корпоратив"),
                            ("PRIVATE", "Частное"),
                        ],
                        default="WEDDING",
                        max_length=64,
                        verbose_name="Тип проекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("NATURE", "Природа"),
                            ("COUNTRYSIDE", "Сельская местность"),
                            ("FOREST", "Лес"),
                            ("WATERSIDE", "Берег моря"),
                            ("MOUNTAINS", "Горы"),
                            ("ABROAD", "За границей"),
                            ("ESTATE", "Поместье"),
                            ("VILLA", "Вилла"),
                            ("RESTAURANT", "Ресторан"),
                        ],
                        max_length=64,
                        unique=True,
                        verbose_name="Название тэга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.ImageField(
                        unique=True,
                        upload_to="storage/images",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="agency.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинку",
                "verbose_name_plural": "Картинки",
                "db_table": "images",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="agency.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "db_table": "reviews",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                related_name="projects", to="agency.tag", verbose_name="Тэги проекта"
            ),
        ),
    ]
