# Generated by Django 5.1.5 on 2025-01-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("phone", models.CharField(max_length=64)),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "feedbacks",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "images",
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=256)),
                ("media", models.CharField(max_length=256)),
                ("media_link", models.CharField(max_length=256)),
                ("preview_image", models.CharField(max_length=512)),
                ("preview_link", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "medias",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "reviews",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("preview_image", models.CharField(max_length=512)),
                ("title", models.CharField(max_length=256)),
                ("descritpion", models.CharField(max_length=512)),
                ("customer", models.CharField(max_length=64)),
                ("place", models.CharField(max_length=64)),
                ("photographer", models.CharField(max_length=64)),
                ("video_url", models.CharField(max_length=512)),
                ("full_description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WEDDING", "WEDDING"),
                            ("CORPORATE", "CORPORATE"),
                            ("PRIVATE", "PRIVATE"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="agency.review"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(related_name="projects", to="agency.tag"),
                ),
            ],
            options={
                "db_table": "projects",
            },
        ),
    ]
