# Generated by Django 5.1.5 on 2025-01-30 18:20

import agency.common.validators.video
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="video",
            field=models.URLField(
                blank=True,
                max_length=512,
                null=True,
                validators=[agency.common.validators.video.rutube_url_validator],
                verbose_name="Ссылка на видео проекта с Rutube",
            ),
        ),
    ]
