# Generated by Django 5.1.5 on 2025-01-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="project",
            name="preview_image",
            field=models.ImageField(
                max_length=512,
                upload_to="storage/images",
                verbose_name="Превью проекта",
            ),
        ),
    ]
