# Generated by Django 5.1.5 on 2025-01-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_alter_image_id_alter_media_id_alter_project_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="preview_image",
            field=models.ImageField(
                unique=True, upload_to="data/images", verbose_name="Превью проекта"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="video_url",
            field=models.URLField(
                max_length=512, verbose_name="Ссылка на видео проекта"
            ),
        ),
    ]
