# Generated by Django 4.2 on 2025-02-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_alter_project_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.ImageField(
                max_length=512, upload_to="storage/images", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                related_name="projects", to="agency.tag", verbose_name="Тэги проекта ()"
            ),
        ),
    ]
