# Generated by Django 4.2 on 2025-02-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0003_alter_image_name_alter_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата публикации статьи"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="link",
            field=models.URLField(
                blank=True, max_length=512, null=True, verbose_name="Ссылка на статью"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Название СМИ"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="storage/images",
                verbose_name="Картинка СМИ",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="storage/images",
                verbose_name="Скриншот статьи",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="title",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Заголовок статьи"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="customer",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Заказчик проекта"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Описание проекта"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="full_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Полное описание проекта"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="photographer",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Фотограф"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="place",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Площадка проведения проекта",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="storage/images",
                verbose_name="Превью проекта",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="agency.tag",
                verbose_name="Тэги проекта",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Заголовок проекта"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="storage/images",
                verbose_name="Картинка к отзыву",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст отзыва"),
        ),
    ]
