# Generated by Django 4.2 on 2025-02-15 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0004_alter_media_date_alter_media_link_alter_media_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
