# Generated by Django 4.2 on 2025-02-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0004_alter_media_date_alter_media_link_alter_media_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ["order"],
                "verbose_name": "Картинка проекта",
                "verbose_name_plural": "Картинки проектов",
            },
        ),
        migrations.AddField(
            model_name="image",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
