# Generated by Django 4.2 on 2026-02-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0007_alter_project_options_alter_project_full_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-order"],
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
